### ISSUE TITLE
Importing test library "Rammbock" failed

### ISSUE THREAD

**Issue by Tina0824** [robotframework/Rammbock#66]
Hello
Importing test library 'Rammbock' failed: AttributeError: 'module' object has no attribute 'librarylogger'
Any idea on how to resolve this problem?
Thank you!

**Comment by jkohvakk** [comment]
Hi Tina,

Can you tell a bit more:

- Include full backtrace
- What kind of environment do you use (Windows, Linux, OSX)?
- Which Python version (Rammbock currently only supports Python 2.7)
- Which Robot version?
- Which Rammbock version?
- How did you install Rammbock (pip or checkout from github and setup.py
install)

-Janne

2017-05-19 5:06 GMT+03:00 Tina0824 <notifications@github.com>:

**Comment by Tina0824** [comment]
Thanks for you quick response,following is relevant infomation:
environment is windows
python2.7 
robot 2.8
Rammbock 0.4.0.1
I am used setup.py install Rammbock
But I installed Rammbock version 0.3.0 is ok

**Comment by jkohvakk** [comment]
Hi,

Sorry, I do not have a windows environment with Robot and Python at hand. Could you also include the full backtrace of the problem (run pybot with -L TRACE option)? Thanks!

-Janne

**Comment by Tina0824** [comment]
Hi Janne,

Thank you 
 I have solved this problem. I installed a lower version of Rammbock.
Thank you so much!

-Tina
